apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUMvakNDQWVhZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwcmRXSmwKY201bGRHVnpNQjRYRFRJek1ESXhOVEF4TkRBeU5Wb1hEVE16TURJeE1qQXhOREF5TlZvd0ZURVRNQkVHQTFVRQpBeE1LYTNWaVpYSnVaWFJsY3pDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBT09WCi9JaFRXSEtLNkdGa2ZZYWRYYVJGa0FyY3QvMWlrMnFFTmxUNFZ6T3BNZFg0Zlc5VFNoenZmb0QxNG5Pcmk4STYKZnYzR3A1ZnEvS2tnWDlYeUQvTWZYaEJCZTR0QjFoaVdIUlEyVEgwNzZhdXNNeWFmQWhJSWF4LzhqSGxYZjZzVgpKZFE1cWVxbDdYOUJBQW43R2Q4d0dKanZtd0k1cm5uMEE0QkJaMFFPa2QvTmhSN3E1WFJHNlRMYk1YUE4rZUxqCjdhdzdXSU9WTzlwVTJtWDNWQTNiSWFiSDlFT2c0cnVCdnI0b0VEVG84cktCSzRVckQxYnM1N2lId0dNYndTLysKU044SFJpUmhocjVxMTdzdDBPbnQvWEZYWWViV0c2dTBZazUwcEhCRW9qQzNiYXVUcVB3TUgrVTBTT3dZbHpobQpSdjNidkl1UzJYYmM5b1hPNnNjQ0F3RUFBYU5aTUZjd0RnWURWUjBQQVFIL0JBUURBZ0trTUE4R0ExVWRFd0VCCi93UUZNQU1CQWY4d0hRWURWUjBPQkJZRUZNMERoYWhBc21waDNsaTZWbGorcy8zdjllcFBNQlVHQTFVZEVRUU8KTUF5Q0NtdDFZbVZ5Ym1WMFpYTXdEUVlKS29aSWh2Y05BUUVMQlFBRGdnRUJBR3hLS3lKMi9kL2d0QlpKZmJJMApmRnRUQVN4aGVRMnBHSW1vUEt5Z3oxclBUWC9xTm5oZHdvcWdjYWJEenZNUjhZcUtoMU40MWhNWDNmbEdLRHI2Ck5CdHN6TGgwL1NNZzdndnBNTmJtRVRYZzZ0RWUyRVphekd4RzBBTG0xTmFSVTVxSVZrbTgzN2QyVjZVNVZqaFIKQm14MmpHUnMxZW92Z21ieFNYcjdIVkFpN3EyaUpEck1RM0JmL3EvOEFLaGg5ZmxHa01EL2RIR3pRMHJlZFZNUApYRjJrVTVrUDEvM3ozQVJKWkpvZkkvcEFrWW96OHk3YlVncUVobjdvNnc5SDlCdCtva3U3a2cwa2ZMbkNKZmxkClQ5Wm95Z21jZW8zNkhZT21US1l0VFdBbkdNWmxjS1dPdjhjTGtYZEJrNXFHbldDend0cDRrU2wzM203T0QzaDkKUDJVPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    server: https://F659641B6C7D69DC36EF87298FFF0AB8.gr7.us-west-1.eks.amazonaws.com
  name: arn:aws:eks:us-west-1:405223155995:cluster/eks-cluster
contexts:
- context:
    cluster: arn:aws:eks:us-west-1:405223155995:cluster/eks-cluster
    user: arn:aws:eks:us-west-1:405223155995:cluster/eks-cluster
  name: arn:aws:eks:us-west-1:405223155995:cluster/eks-cluster
current-context: arn:aws:eks:us-west-1:405223155995:cluster/eks-cluster
kind: Config
preferences: {}
users:
- name: arn:aws:eks:us-west-1:405223155995:cluster/eks-cluster
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
      - --region
      - us-west-1
      - eks
      - get-token
      - --cluster-name
      - eks-cluster
      command: aws
      env:
      - name: AWS_PROFILE
        value: charliedazzle
